### ISSUE TITLE
Crash when processing opacity in keyframe animation

### ISSUE THREAD

**Issue by lewisl9029** [cssdream/cssgrace#7]
cssgrace seems to be crashing on the following snippet:
```css
@keyframes fadein {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}
```

Here's the full stack trace: 
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot call method 'replace' of undefined
    at ieOpacityHack (/toc/node_modules/cssgrace/lib/index.js:268:32)
    at /toc/node_modules/cssgrace/lib/index.js:456:5
    at /toc/node_modules/postcss/lib/container.js:162:24
    at /toc/node_modules/postcss/lib/container.js:132:20
    at Rule.Container.each (/toc/node_modules/postcss/lib/container.js:110:16)
    at Rule.Container.eachInside (/toc/node_modules/postcss/lib/container.js:131:17)
    at Rule.Container.eachDecl (/toc/node_modules/postcss/lib/container.js:160:19)
    at cssgraceRule (/toc/node_modules/cssgrace/lib/index.js:453:8)
    at /toc/node_modules/postcss/lib/container.js:197:22
    at /toc/node_modules/postcss/lib/container.js:132:20
```

Let me know if you need more info.

**Comment by yisibl** [comment]
Please update gulp-postcss or grunt-postcss.Make sure they have supported PostCSS 4.0+
